### ISSUE TITLE
Instructions followed, still Connection in progress: 1-2 - Am I missing something?

### ISSUE THREAD

**Issue by noxinias** [mrhteriyaki/RA3LANHelper#1]
Goal: Local coop red alert 3
Setup: 
Ports 40000-40050 forwarded for client at router
Ports 50000-50050 forwarded for host at router
Router has UPNP enabled.
CnC Relay started, using corresponding port for machine, host file enabled
CnC online logged into, both machines, 

Process:
Launch cnc online, using its hooked red alert 3
Can invite client to match upto the "ready" button works and is reflected on both machines - mission lobby chat messages function.
Error shown "Connection in progress: 1-2 on attempting to start.

I suspect maybe I am missing a step with the in-game network properties - I attempted several permutations with no luck
what is ideal/expected here? 
Setting the ip and corresponding port? leaving them empty?
Is there a log file accessible?

**Comment by mrhteriyaki** [comment]
IP/Port should be clear in-game settings.
I can confirm the related settings in teh Options.INI file at (C:\Users\<username>\AppData\Roaming\Red Alert 3\Profiles\<ra3 user>) are:

FirewallPortOverride = 0
GameSpyIPAddress = 0.0.0.0

Steps followed look correct.
UPNP wont be required if the forwards have been done manually.
Can you confirm UDP not TCP is used for port forwards and also have a regular public IP (not behind a CG-NAT)?

You can also get console output using the CNCLocalRelay.exe program rather than the GUI tool.
eg: CnCLocalRelay.exe 50000
It should show log entries when connections are made.

**Comment by noxinias** [comment]
Thank you for your response, I imagine there's going to be more of an influx of people trying to get RA3 going since the release on steam, If I manage it I'll spread the word with a step-by-step.

I am attempting further troubleshooting on my own using your advice to run via command line. 
I can confirm UDP forwards are set up from start of range + 50.
I can confirm port override and address in the profile match what your wrote, 0, 0.0.0.0

No entries are shown in the command line (besides the original one which states the natneg server's current ip) when making (or attempting to make) a connection, leading me to thinking there is some other connectivity issue I need to address.

Is there some shorthand way I can test the relay to natneg.server.cnc-online.net?

**Comment by mrhteriyaki** [comment]
If you ping the natneg address in a shell does it resolve to 127.0.0.1?

eg: open command prompt and run
ping natneg.server.cnc-online.net

Should show reply from 127.0.0.1
I've found an issue when the hosts file has been edited and does not finish with a newline it will append to an existing line.

Or just check the hosts file at C:\Windows\System32\drivers\etc\hosts

Other issues might be related to the nat loopback, can you confirm you've just got a single router and not multiple routers in series? (Double nat)

**Comment by mrhteriyaki** [comment]
I've re-tested it tonight to confirm it does actually work, so no issues with natneg server.
The client side should show "new outbound connection" entries in the console output when joining.

Once the connection is completed both sides should show "new peer connection" once the connection is established.

Also might be an idea to check windows firewall is not blocking the relay.
Windows Key + R (Opens run)
Type resmon and hit enter
Under network, check the box next to CncLocalRelay.exe
Expand the listening ports box.
Check that the firewall status is "Allowed, not restricted" particuarlly for port 27901.

**Comment by jpdribbler** [comment]
fixed, caused by shitty windows firewall. Works great. thank you!!
